# Generated by Django 4.1.9 on 2023-06-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_registromodel_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registromodel',
            name='professor',
            field=models.CharField(choices=[('Orlando Saraiva Jr', 'Orlando Saraiva Jr'), ('Thiago Mendes', 'Thiago Mendes'), ('Esdras Silva', 'Esdras Silva'), ('Ana Celia Portes', 'Ana Celia Portes')], max_length=100, verbose_name='Nome Professor'),
        ),
    ]
